DROP TABLE pluto_16v2_TEMPLATE;
CREATE TABLE pluto_16v2_TEMPLATE
( 
  Borough CHAR(2),
  Block DECIMAL(5),
  Lot DECIMAL(4),
  CD DECIMAL(3),
  CT2010 CHAR(7),
  CB2010 CHAR(5),
  SchoolDist DECIMAL(2),
  Council DECIMAL(2),
  ZipCode CHAR(5),
  FireComp CHAR(4),
  PolicePrct DECIMAL(3),
  HealthArea DECIMAL(4),
  SanitBoro CHAR(1),
  SanitDistrict CHAR(2),
  SanitSub CHAR(2),
  Address CHAR(28),
  ZoneDist1 CHAR(9),
  ZoneDist2 CHAR(9),
  ZoneDist3 CHAR(9),
  ZoneDist4 CHAR(9),
  Overlay1 CHAR(4),
  Overlay2 CHAR(4),
  SPDist1 CHAR(6),
  SPDist2 CHAR(6),
  SPDist3 CHAR(6),
  LtdHeight CHAR(5),
  SplitZone CHAR(1),
  BldgClass CHAR(2),
  LandUse CHAR(2),
  Easements DECIMAL(2),
  OwnerType CHAR(1),
  OwnerName CHAR(21),
  LotArea DECIMAL(9),
  BldgArea DECIMAL(11),
  ComArea DECIMAL(11),
  ResArea DECIMAL(11),
  OfficeArea DECIMAL(11),
  RetailArea DECIMAL(11),
  GarageArea DECIMAL(11),
  StrgeArea DECIMAL(11),
  FactryArea DECIMAL(11),
  OtherArea DECIMAL(11),
  AreaSource CHAR(1),
  NumBldgs DECIMAL(5),
  NumFloors DECIMAL(5,2),
  UnitsRes DECIMAL(5),
  UnitsTotal DECIMAL(5),
  LotFront DECIMAL(6,2),
  LotDepth DECIMAL(6,2),
  BldgFront DECIMAL(6,2),
  BldgDepth DECIMAL(6,2),
  Ext CHAR(2),
  ProxCode CHAR(1),
  IrrLotCode CHAR(1),
  LotType CHAR(1),
  BsmtCode CHAR(1),
  AssessLand DECIMAL(11),
  AssessTot DECIMAL(11),
  ExemptLand DECIMAL(11),
  ExemptTot DECIMAL(11),
  YearBuilt INT(4),
  YearAlter1 INT(4),
  YearAlter2 INT(4),
  HistDist CHAR(40),
  Landmark CHAR(35),
  BuiltFAR DECIMAL(6,2),
  ResidFAR DECIMAL(4,2),
  CommFAR DECIMAL(4,2),
  FacilFAR DECIMAL(4,2),
  BoroCode DECIMAL(1),
  BBL DECIMAL(10),
  CondoNo DECIMAL(5),
  Tract2010 CHAR(6),
  XCoord DECIMAL(7),
  YCoord DECIMAL(7),
  ZoneMap CHAR(3),
  ZMCode CHAR(1),
  Sanborn CHAR(8),
  TaxMap CHAR(5),
  EDesigNum CHAR(5),
  APPBBL DECIMAL(10),
  APPDate DATE,
  PLUTOMapID DECIMAL(1),
  Version CHAR(6)
);

drop table pluto_16v2_BK;
drop table pluto_16v2_BX;
drop table pluto_16v2_MN;
drop table pluto_16v2_SI;
drop table pluto_16v2_QN;

create table pluto_16v2_BK as select * from pluto_16v2_TEMPLATE where 1=0;
create table pluto_16v2_BX as select * from pluto_16v2_TEMPLATE where 1=0;
create table pluto_16v2_MN as select * from pluto_16v2_TEMPLATE where 1=0;
create table pluto_16v2_SI as select * from pluto_16v2_TEMPLATE where 1=0;
create table pluto_16v2_QN as select * from pluto_16v2_TEMPLATE where 1=0;

create or replace view pluto_BK as select * from pluto_16v2_BK;
create or replace view pluto_BX as select * from pluto_16v2_BX;
create or replace view pluto_MN as select * from pluto_16v2_MN;
create or replace view pluto_SI as select * from pluto_16v2_SI;
create or replace view pluto_QN as select * from pluto_16v2_QN;

create or replace view pluto as 
	select * from pluto_BK UNION ALL
	select * from pluto_BX UNION ALL
	select * from pluto_MN UNION ALL
	select * from pluto_SI UNION ALL
	select * from pluto_QN;

load data local infile '../BK.csv' into table pluto_BK fields terminated by ',' optionally enclosed by '"' escaped by '\\' lines terminated by '\n' starting by '' ignore 1 rows
(@vBorough, @vBlock, @vLot, @vCD, @vCT2010, @vCB2010, @vSchoolDist, @vCouncil, @vZipCode, @vFireComp, @vPolicePrct, @vHealthArea, @vSanitBoro, @vSanitDistrict, @vSanitSub, @vAddress, @vZoneDist1, @vZoneDist2, @vZoneDist3, @vZoneDist4, @vOverlay1, @vOverlay2, @vSPDist1, @vSPDist2, @vSPDist3, @vLtdHeight, @vSplitZone, @vBldgClass, @vLandUse, @vEasements, @vOwnerType, @vOwnerName, @vLotArea, @vBldgArea, @vComArea, @vResArea, @vOfficeArea, @vRetailArea, @vGarageArea, @vStrgeArea, @vFactryArea, @vOtherArea, @vAreaSource, @vNumBldgs, @vNumFloors, @vUnitsRes, @vUnitsTotal, @vLotFront, @vLotDepth, @vBldgFront, @vBldgDepth, @vExt, @vProxCode, @vIrrLotCode, @vLotType, @vBsmtCode, @vAssessLand, @vAssessTot, @vExemptLand, @vExemptTot, @vYearBuilt, @vYearAlter1, @vYearAlter2, @vHistDist, @vLandmark, @vBuiltFAR, @vResidFAR, @vCommFAR, @vFacilFAR, @vBoroCode, @vBBL, @vCondoNo, @vTract2010, @vXCoord, @vYCoord, @vZoneMap, @vZMCode, @vSanborn, @vTaxMap, @vEDesigNum, @vAPPBBL, @vAPPDate, @vPLUTOMapID, @vVersion)
SET
Borough	= nullif(@vBorough,''),
Block	= nullif(@vBlock,''),
Lot	= nullif(@vLot,''),
CD	= nullif(@vCD,''),
CT2010	= nullif(@vCT2010,''),
CB2010	= nullif(@vCB2010,''),
SchoolDist	= nullif(@vSchoolDist,''),
Council	= nullif(@vCouncil,''),
ZipCode	= nullif(@vZipCode,''),
FireComp	= nullif(@vFireComp,''),
PolicePrct	= nullif(@vPolicePrct,''),
HealthArea	= nullif(@vHealthArea,''),
SanitBoro	= nullif(@vSanitBoro,''),
SanitDistrict	= nullif(@vSanitDistrict,''),
SanitSub	= nullif(@vSanitSub,''),
Address	= nullif(@vAddress,''),
ZoneDist1	= nullif(@vZoneDist1,''),
ZoneDist2	= nullif(@vZoneDist2,''),
ZoneDist3	= nullif(@vZoneDist3,''),
ZoneDist4	= nullif(@vZoneDist4,''),
Overlay1	= nullif(@vOverlay1,''),
Overlay2	= nullif(@vOverlay2,''),
SPDist1	= nullif(@vSPDist1,''),
SPDist2	= nullif(@vSPDist2,''),
SPDist3	= nullif(@vSPDist3,''),
LtdHeight	= nullif(@vLtdHeight,''),
SplitZone	= nullif(@vSplitZone,''),
BldgClass	= nullif(@vBldgClass,''),
LandUse	= nullif(@vLandUse,''),
Easements	= nullif(@vEasements,''),
OwnerType	= nullif(@vOwnerType,''),
OwnerName	= nullif(@vOwnerName,''),
LotArea	= nullif(@vLotArea,''),
BldgArea	= nullif(@vBldgArea,''),
ComArea	= nullif(@vComArea,''),
ResArea	= nullif(@vResArea,''),
OfficeArea	= nullif(@vOfficeArea,''),
RetailArea	= nullif(@vRetailArea,''),
GarageArea	= nullif(@vGarageArea,''),
StrgeArea	= nullif(@vStrgeArea,''),
FactryArea	= nullif(@vFactryArea,''),
OtherArea	= nullif(@vOtherArea,''),
AreaSource	= nullif(@vAreaSource,''),
NumBldgs	= nullif(@vNumBldgs,''),
NumFloors	= nullif(@vNumFloors,''),
UnitsRes	= nullif(@vUnitsRes,''),
UnitsTotal	= nullif(@vUnitsTotal,''),
LotFront	= nullif(@vLotFront,''),
LotDepth	= nullif(@vLotDepth,''),
BldgFront	= nullif(@vBldgFront,''),
BldgDepth	= nullif(@vBldgDepth,''),
Ext	= nullif(@vExt,''),
ProxCode	= nullif(@vProxCode,''),
IrrLotCode	= nullif(@vIrrLotCode,''),
LotType	= nullif(@vLotType,''),
BsmtCode	= nullif(@vBsmtCode,''),
AssessLand	= nullif(@vAssessLand,''),
AssessTot	= nullif(@vAssessTot,''),
ExemptLand	= nullif(@vExemptLand,''),
ExemptTot	= nullif(@vExemptTot,''),
YearBuilt	= nullif(@vYearBuilt,''),
YearAlter1	= nullif(@vYearAlter1,''),
YearAlter2	= nullif(@vYearAlter2,''),
HistDist	= nullif(@vHistDist,''),
Landmark	= nullif(@vLandmark,''),
BuiltFAR	= nullif(@vBuiltFAR,''),
ResidFAR	= nullif(@vResidFAR,''),
CommFAR	= nullif(@vCommFAR,''),
FacilFAR	= nullif(@vFacilFAR,''),
BoroCode	= nullif(@vBoroCode,''),
BBL	= nullif(@vBBL,''),
CondoNo	= nullif(@vCondoNo,''),
Tract2010	= nullif(@vTract2010,''),
XCoord	= nullif(@vXCoord,''),
YCoord	= nullif(@vYCoord,''),
ZoneMap	= nullif(@vZoneMap,''),
ZMCode	= nullif(@vZMCode,''),
Sanborn	= nullif(@vSanborn,''),
TaxMap	= nullif(@vTaxMap,''),
EDesigNum	= nullif(@vEDesigNum,''),
APPBBL	= nullif(@vAPPBBL,''),
APPDate	= STR_TO_DATE(nullif(@vAPPDate,''),'%m/%d/%Y'),
PLUTOMapID	= nullif(@vPLUTOMapID,''),
Version	= nullif(@vVersion,'');

load data local infile '../BX.csv' into table pluto_BX fields terminated by ',' optionally enclosed by '"' escaped by '\\' lines terminated by '\n' starting by '' ignore 1 rows
(@vBorough, @vBlock, @vLot, @vCD, @vCT2010, @vCB2010, @vSchoolDist, @vCouncil, @vZipCode, @vFireComp, @vPolicePrct, @vHealthArea, @vSanitBoro, @vSanitDistrict, @vSanitSub, @vAddress, @vZoneDist1, @vZoneDist2, @vZoneDist3, @vZoneDist4, @vOverlay1, @vOverlay2, @vSPDist1, @vSPDist2, @vSPDist3, @vLtdHeight, @vSplitZone, @vBldgClass, @vLandUse, @vEasements, @vOwnerType, @vOwnerName, @vLotArea, @vBldgArea, @vComArea, @vResArea, @vOfficeArea, @vRetailArea, @vGarageArea, @vStrgeArea, @vFactryArea, @vOtherArea, @vAreaSource, @vNumBldgs, @vNumFloors, @vUnitsRes, @vUnitsTotal, @vLotFront, @vLotDepth, @vBldgFront, @vBldgDepth, @vExt, @vProxCode, @vIrrLotCode, @vLotType, @vBsmtCode, @vAssessLand, @vAssessTot, @vExemptLand, @vExemptTot, @vYearBuilt, @vYearAlter1, @vYearAlter2, @vHistDist, @vLandmark, @vBuiltFAR, @vResidFAR, @vCommFAR, @vFacilFAR, @vBoroCode, @vBBL, @vCondoNo, @vTract2010, @vXCoord, @vYCoord, @vZoneMap, @vZMCode, @vSanborn, @vTaxMap, @vEDesigNum, @vAPPBBL, @vAPPDate, @vPLUTOMapID, @vVersion)
SET
Borough	= nullif(@vBorough,''),
Block	= nullif(@vBlock,''),
Lot	= nullif(@vLot,''),
CD	= nullif(@vCD,''),
CT2010	= nullif(@vCT2010,''),
CB2010	= nullif(@vCB2010,''),
SchoolDist	= nullif(@vSchoolDist,''),
Council	= nullif(@vCouncil,''),
ZipCode	= nullif(@vZipCode,''),
FireComp	= nullif(@vFireComp,''),
PolicePrct	= nullif(@vPolicePrct,''),
HealthArea	= nullif(@vHealthArea,''),
SanitBoro	= nullif(@vSanitBoro,''),
SanitDistrict	= nullif(@vSanitDistrict,''),
SanitSub	= nullif(@vSanitSub,''),
Address	= nullif(@vAddress,''),
ZoneDist1	= nullif(@vZoneDist1,''),
ZoneDist2	= nullif(@vZoneDist2,''),
ZoneDist3	= nullif(@vZoneDist3,''),
ZoneDist4	= nullif(@vZoneDist4,''),
Overlay1	= nullif(@vOverlay1,''),
Overlay2	= nullif(@vOverlay2,''),
SPDist1	= nullif(@vSPDist1,''),
SPDist2	= nullif(@vSPDist2,''),
SPDist3	= nullif(@vSPDist3,''),
LtdHeight	= nullif(@vLtdHeight,''),
SplitZone	= nullif(@vSplitZone,''),
BldgClass	= nullif(@vBldgClass,''),
LandUse	= nullif(@vLandUse,''),
Easements	= nullif(@vEasements,''),
OwnerType	= nullif(@vOwnerType,''),
OwnerName	= nullif(@vOwnerName,''),
LotArea	= nullif(@vLotArea,''),
BldgArea	= nullif(@vBldgArea,''),
ComArea	= nullif(@vComArea,''),
ResArea	= nullif(@vResArea,''),
OfficeArea	= nullif(@vOfficeArea,''),
RetailArea	= nullif(@vRetailArea,''),
GarageArea	= nullif(@vGarageArea,''),
StrgeArea	= nullif(@vStrgeArea,''),
FactryArea	= nullif(@vFactryArea,''),
OtherArea	= nullif(@vOtherArea,''),
AreaSource	= nullif(@vAreaSource,''),
NumBldgs	= nullif(@vNumBldgs,''),
NumFloors	= nullif(@vNumFloors,''),
UnitsRes	= nullif(@vUnitsRes,''),
UnitsTotal	= nullif(@vUnitsTotal,''),
LotFront	= nullif(@vLotFront,''),
LotDepth	= nullif(@vLotDepth,''),
BldgFront	= nullif(@vBldgFront,''),
BldgDepth	= nullif(@vBldgDepth,''),
Ext	= nullif(@vExt,''),
ProxCode	= nullif(@vProxCode,''),
IrrLotCode	= nullif(@vIrrLotCode,''),
LotType	= nullif(@vLotType,''),
BsmtCode	= nullif(@vBsmtCode,''),
AssessLand	= nullif(@vAssessLand,''),
AssessTot	= nullif(@vAssessTot,''),
ExemptLand	= nullif(@vExemptLand,''),
ExemptTot	= nullif(@vExemptTot,''),
YearBuilt	= nullif(@vYearBuilt,''),
YearAlter1	= nullif(@vYearAlter1,''),
YearAlter2	= nullif(@vYearAlter2,''),
HistDist	= nullif(@vHistDist,''),
Landmark	= nullif(@vLandmark,''),
BuiltFAR	= nullif(@vBuiltFAR,''),
ResidFAR	= nullif(@vResidFAR,''),
CommFAR	= nullif(@vCommFAR,''),
FacilFAR	= nullif(@vFacilFAR,''),
BoroCode	= nullif(@vBoroCode,''),
BBL	= nullif(@vBBL,''),
CondoNo	= nullif(@vCondoNo,''),
Tract2010	= nullif(@vTract2010,''),
XCoord	= nullif(@vXCoord,''),
YCoord	= nullif(@vYCoord,''),
ZoneMap	= nullif(@vZoneMap,''),
ZMCode	= nullif(@vZMCode,''),
Sanborn	= nullif(@vSanborn,''),
TaxMap	= nullif(@vTaxMap,''),
EDesigNum	= nullif(@vEDesigNum,''),
APPBBL	= nullif(@vAPPBBL,''),
APPDate	= STR_TO_DATE(nullif(@vAPPDate,''),'%m/%d/%Y'),
PLUTOMapID	= nullif(@vPLUTOMapID,''),
Version	= nullif(@vVersion,'');

load data local infile '../MN.csv' into table pluto_MN fields terminated by ',' optionally enclosed by '"' escaped by '\\' lines terminated by '\n' starting by '' ignore 1 rows
(@vBorough, @vBlock, @vLot, @vCD, @vCT2010, @vCB2010, @vSchoolDist, @vCouncil, @vZipCode, @vFireComp, @vPolicePrct, @vHealthArea, @vSanitBoro, @vSanitDistrict, @vSanitSub, @vAddress, @vZoneDist1, @vZoneDist2, @vZoneDist3, @vZoneDist4, @vOverlay1, @vOverlay2, @vSPDist1, @vSPDist2, @vSPDist3, @vLtdHeight, @vSplitZone, @vBldgClass, @vLandUse, @vEasements, @vOwnerType, @vOwnerName, @vLotArea, @vBldgArea, @vComArea, @vResArea, @vOfficeArea, @vRetailArea, @vGarageArea, @vStrgeArea, @vFactryArea, @vOtherArea, @vAreaSource, @vNumBldgs, @vNumFloors, @vUnitsRes, @vUnitsTotal, @vLotFront, @vLotDepth, @vBldgFront, @vBldgDepth, @vExt, @vProxCode, @vIrrLotCode, @vLotType, @vBsmtCode, @vAssessLand, @vAssessTot, @vExemptLand, @vExemptTot, @vYearBuilt, @vYearAlter1, @vYearAlter2, @vHistDist, @vLandmark, @vBuiltFAR, @vResidFAR, @vCommFAR, @vFacilFAR, @vBoroCode, @vBBL, @vCondoNo, @vTract2010, @vXCoord, @vYCoord, @vZoneMap, @vZMCode, @vSanborn, @vTaxMap, @vEDesigNum, @vAPPBBL, @vAPPDate, @vPLUTOMapID, @vVersion)
SET
Borough	= nullif(@vBorough,''),
Block	= nullif(@vBlock,''),
Lot	= nullif(@vLot,''),
CD	= nullif(@vCD,''),
CT2010	= nullif(@vCT2010,''),
CB2010	= nullif(@vCB2010,''),
SchoolDist	= nullif(@vSchoolDist,''),
Council	= nullif(@vCouncil,''),
ZipCode	= nullif(@vZipCode,''),
FireComp	= nullif(@vFireComp,''),
PolicePrct	= nullif(@vPolicePrct,''),
HealthArea	= nullif(@vHealthArea,''),
SanitBoro	= nullif(@vSanitBoro,''),
SanitDistrict	= nullif(@vSanitDistrict,''),
SanitSub	= nullif(@vSanitSub,''),
Address	= nullif(@vAddress,''),
ZoneDist1	= nullif(@vZoneDist1,''),
ZoneDist2	= nullif(@vZoneDist2,''),
ZoneDist3	= nullif(@vZoneDist3,''),
ZoneDist4	= nullif(@vZoneDist4,''),
Overlay1	= nullif(@vOverlay1,''),
Overlay2	= nullif(@vOverlay2,''),
SPDist1	= nullif(@vSPDist1,''),
SPDist2	= nullif(@vSPDist2,''),
SPDist3	= nullif(@vSPDist3,''),
LtdHeight	= nullif(@vLtdHeight,''),
SplitZone	= nullif(@vSplitZone,''),
BldgClass	= nullif(@vBldgClass,''),
LandUse	= nullif(@vLandUse,''),
Easements	= nullif(@vEasements,''),
OwnerType	= nullif(@vOwnerType,''),
OwnerName	= nullif(@vOwnerName,''),
LotArea	= nullif(@vLotArea,''),
BldgArea	= nullif(@vBldgArea,''),
ComArea	= nullif(@vComArea,''),
ResArea	= nullif(@vResArea,''),
OfficeArea	= nullif(@vOfficeArea,''),
RetailArea	= nullif(@vRetailArea,''),
GarageArea	= nullif(@vGarageArea,''),
StrgeArea	= nullif(@vStrgeArea,''),
FactryArea	= nullif(@vFactryArea,''),
OtherArea	= nullif(@vOtherArea,''),
AreaSource	= nullif(@vAreaSource,''),
NumBldgs	= nullif(@vNumBldgs,''),
NumFloors	= nullif(@vNumFloors,''),
UnitsRes	= nullif(@vUnitsRes,''),
UnitsTotal	= nullif(@vUnitsTotal,''),
LotFront	= nullif(@vLotFront,''),
LotDepth	= nullif(@vLotDepth,''),
BldgFront	= nullif(@vBldgFront,''),
BldgDepth	= nullif(@vBldgDepth,''),
Ext	= nullif(@vExt,''),
ProxCode	= nullif(@vProxCode,''),
IrrLotCode	= nullif(@vIrrLotCode,''),
LotType	= nullif(@vLotType,''),
BsmtCode	= nullif(@vBsmtCode,''),
AssessLand	= nullif(@vAssessLand,''),
AssessTot	= nullif(@vAssessTot,''),
ExemptLand	= nullif(@vExemptLand,''),
ExemptTot	= nullif(@vExemptTot,''),
YearBuilt	= nullif(@vYearBuilt,''),
YearAlter1	= nullif(@vYearAlter1,''),
YearAlter2	= nullif(@vYearAlter2,''),
HistDist	= nullif(@vHistDist,''),
Landmark	= nullif(@vLandmark,''),
BuiltFAR	= nullif(@vBuiltFAR,''),
ResidFAR	= nullif(@vResidFAR,''),
CommFAR	= nullif(@vCommFAR,''),
FacilFAR	= nullif(@vFacilFAR,''),
BoroCode	= nullif(@vBoroCode,''),
BBL	= nullif(@vBBL,''),
CondoNo	= nullif(@vCondoNo,''),
Tract2010	= nullif(@vTract2010,''),
XCoord	= nullif(@vXCoord,''),
YCoord	= nullif(@vYCoord,''),
ZoneMap	= nullif(@vZoneMap,''),
ZMCode	= nullif(@vZMCode,''),
Sanborn	= nullif(@vSanborn,''),
TaxMap	= nullif(@vTaxMap,''),
EDesigNum	= nullif(@vEDesigNum,''),
APPBBL	= nullif(@vAPPBBL,''),
APPDate	= STR_TO_DATE(nullif(@vAPPDate,''),'%m/%d/%Y'),
PLUTOMapID	= nullif(@vPLUTOMapID,''),
Version	= nullif(@vVersion,'');

load data local infile '../SI.csv' into table pluto_SI fields terminated by ',' optionally enclosed by '"' escaped by '\\' lines terminated by '\n' starting by '' ignore 1 rows
(@vBorough, @vBlock, @vLot, @vCD, @vCT2010, @vCB2010, @vSchoolDist, @vCouncil, @vZipCode, @vFireComp, @vPolicePrct, @vHealthArea, @vSanitBoro, @vSanitDistrict, @vSanitSub, @vAddress, @vZoneDist1, @vZoneDist2, @vZoneDist3, @vZoneDist4, @vOverlay1, @vOverlay2, @vSPDist1, @vSPDist2, @vSPDist3, @vLtdHeight, @vSplitZone, @vBldgClass, @vLandUse, @vEasements, @vOwnerType, @vOwnerName, @vLotArea, @vBldgArea, @vComArea, @vResArea, @vOfficeArea, @vRetailArea, @vGarageArea, @vStrgeArea, @vFactryArea, @vOtherArea, @vAreaSource, @vNumBldgs, @vNumFloors, @vUnitsRes, @vUnitsTotal, @vLotFront, @vLotDepth, @vBldgFront, @vBldgDepth, @vExt, @vProxCode, @vIrrLotCode, @vLotType, @vBsmtCode, @vAssessLand, @vAssessTot, @vExemptLand, @vExemptTot, @vYearBuilt, @vYearAlter1, @vYearAlter2, @vHistDist, @vLandmark, @vBuiltFAR, @vResidFAR, @vCommFAR, @vFacilFAR, @vBoroCode, @vBBL, @vCondoNo, @vTract2010, @vXCoord, @vYCoord, @vZoneMap, @vZMCode, @vSanborn, @vTaxMap, @vEDesigNum, @vAPPBBL, @vAPPDate, @vPLUTOMapID, @vVersion)
SET
Borough	= nullif(@vBorough,''),
Block	= nullif(@vBlock,''),
Lot	= nullif(@vLot,''),
CD	= nullif(@vCD,''),
CT2010	= nullif(@vCT2010,''),
CB2010	= nullif(@vCB2010,''),
SchoolDist	= nullif(@vSchoolDist,''),
Council	= nullif(@vCouncil,''),
ZipCode	= nullif(@vZipCode,''),
FireComp	= nullif(@vFireComp,''),
PolicePrct	= nullif(@vPolicePrct,''),
HealthArea	= nullif(@vHealthArea,''),
SanitBoro	= nullif(@vSanitBoro,''),
SanitDistrict	= nullif(@vSanitDistrict,''),
SanitSub	= nullif(@vSanitSub,''),
Address	= nullif(@vAddress,''),
ZoneDist1	= nullif(@vZoneDist1,''),
ZoneDist2	= nullif(@vZoneDist2,''),
ZoneDist3	= nullif(@vZoneDist3,''),
ZoneDist4	= nullif(@vZoneDist4,''),
Overlay1	= nullif(@vOverlay1,''),
Overlay2	= nullif(@vOverlay2,''),
SPDist1	= nullif(@vSPDist1,''),
SPDist2	= nullif(@vSPDist2,''),
SPDist3	= nullif(@vSPDist3,''),
LtdHeight	= nullif(@vLtdHeight,''),
SplitZone	= nullif(@vSplitZone,''),
BldgClass	= nullif(@vBldgClass,''),
LandUse	= nullif(@vLandUse,''),
Easements	= nullif(@vEasements,''),
OwnerType	= nullif(@vOwnerType,''),
OwnerName	= nullif(@vOwnerName,''),
LotArea	= nullif(@vLotArea,''),
BldgArea	= nullif(@vBldgArea,''),
ComArea	= nullif(@vComArea,''),
ResArea	= nullif(@vResArea,''),
OfficeArea	= nullif(@vOfficeArea,''),
RetailArea	= nullif(@vRetailArea,''),
GarageArea	= nullif(@vGarageArea,''),
StrgeArea	= nullif(@vStrgeArea,''),
FactryArea	= nullif(@vFactryArea,''),
OtherArea	= nullif(@vOtherArea,''),
AreaSource	= nullif(@vAreaSource,''),
NumBldgs	= nullif(@vNumBldgs,''),
NumFloors	= nullif(@vNumFloors,''),
UnitsRes	= nullif(@vUnitsRes,''),
UnitsTotal	= nullif(@vUnitsTotal,''),
LotFront	= nullif(@vLotFront,''),
LotDepth	= nullif(@vLotDepth,''),
BldgFront	= nullif(@vBldgFront,''),
BldgDepth	= nullif(@vBldgDepth,''),
Ext	= nullif(@vExt,''),
ProxCode	= nullif(@vProxCode,''),
IrrLotCode	= nullif(@vIrrLotCode,''),
LotType	= nullif(@vLotType,''),
BsmtCode	= nullif(@vBsmtCode,''),
AssessLand	= nullif(@vAssessLand,''),
AssessTot	= nullif(@vAssessTot,''),
ExemptLand	= nullif(@vExemptLand,''),
ExemptTot	= nullif(@vExemptTot,''),
YearBuilt	= nullif(@vYearBuilt,''),
YearAlter1	= nullif(@vYearAlter1,''),
YearAlter2	= nullif(@vYearAlter2,''),
HistDist	= nullif(@vHistDist,''),
Landmark	= nullif(@vLandmark,''),
BuiltFAR	= nullif(@vBuiltFAR,''),
ResidFAR	= nullif(@vResidFAR,''),
CommFAR	= nullif(@vCommFAR,''),
FacilFAR	= nullif(@vFacilFAR,''),
BoroCode	= nullif(@vBoroCode,''),
BBL	= nullif(@vBBL,''),
CondoNo	= nullif(@vCondoNo,''),
Tract2010	= nullif(@vTract2010,''),
XCoord	= nullif(@vXCoord,''),
YCoord	= nullif(@vYCoord,''),
ZoneMap	= nullif(@vZoneMap,''),
ZMCode	= nullif(@vZMCode,''),
Sanborn	= nullif(@vSanborn,''),
TaxMap	= nullif(@vTaxMap,''),
EDesigNum	= nullif(@vEDesigNum,''),
APPBBL	= nullif(@vAPPBBL,''),
APPDate	= STR_TO_DATE(nullif(@vAPPDate,''),'%m/%d/%Y'),
PLUTOMapID	= nullif(@vPLUTOMapID,''),
Version	= nullif(@vVersion,'');

load data local infile '../QN.csv' into table pluto_QN fields terminated by ',' optionally enclosed by '"' escaped by '\\' lines terminated by '\n' starting by '' ignore 1 rows
(@vBorough, @vBlock, @vLot, @vCD, @vCT2010, @vCB2010, @vSchoolDist, @vCouncil, @vZipCode, @vFireComp, @vPolicePrct, @vHealthArea, @vSanitBoro, @vSanitDistrict, @vSanitSub, @vAddress, @vZoneDist1, @vZoneDist2, @vZoneDist3, @vZoneDist4, @vOverlay1, @vOverlay2, @vSPDist1, @vSPDist2, @vSPDist3, @vLtdHeight, @vSplitZone, @vBldgClass, @vLandUse, @vEasements, @vOwnerType, @vOwnerName, @vLotArea, @vBldgArea, @vComArea, @vResArea, @vOfficeArea, @vRetailArea, @vGarageArea, @vStrgeArea, @vFactryArea, @vOtherArea, @vAreaSource, @vNumBldgs, @vNumFloors, @vUnitsRes, @vUnitsTotal, @vLotFront, @vLotDepth, @vBldgFront, @vBldgDepth, @vExt, @vProxCode, @vIrrLotCode, @vLotType, @vBsmtCode, @vAssessLand, @vAssessTot, @vExemptLand, @vExemptTot, @vYearBuilt, @vYearAlter1, @vYearAlter2, @vHistDist, @vLandmark, @vBuiltFAR, @vResidFAR, @vCommFAR, @vFacilFAR, @vBoroCode, @vBBL, @vCondoNo, @vTract2010, @vXCoord, @vYCoord, @vZoneMap, @vZMCode, @vSanborn, @vTaxMap, @vEDesigNum, @vAPPBBL, @vAPPDate, @vPLUTOMapID, @vVersion)
SET
Borough	= nullif(@vBorough,''),
Block	= nullif(@vBlock,''),
Lot	= nullif(@vLot,''),
CD	= nullif(@vCD,''),
CT2010	= nullif(@vCT2010,''),
CB2010	= nullif(@vCB2010,''),
SchoolDist	= nullif(@vSchoolDist,''),
Council	= nullif(@vCouncil,''),
ZipCode	= nullif(@vZipCode,''),
FireComp	= nullif(@vFireComp,''),
PolicePrct	= nullif(@vPolicePrct,''),
HealthArea	= nullif(@vHealthArea,''),
SanitBoro	= nullif(@vSanitBoro,''),
SanitDistrict	= nullif(@vSanitDistrict,''),
SanitSub	= nullif(@vSanitSub,''),
Address	= nullif(@vAddress,''),
ZoneDist1	= nullif(@vZoneDist1,''),
ZoneDist2	= nullif(@vZoneDist2,''),
ZoneDist3	= nullif(@vZoneDist3,''),
ZoneDist4	= nullif(@vZoneDist4,''),
Overlay1	= nullif(@vOverlay1,''),
Overlay2	= nullif(@vOverlay2,''),
SPDist1	= nullif(@vSPDist1,''),
SPDist2	= nullif(@vSPDist2,''),
SPDist3	= nullif(@vSPDist3,''),
LtdHeight	= nullif(@vLtdHeight,''),
SplitZone	= nullif(@vSplitZone,''),
BldgClass	= nullif(@vBldgClass,''),
LandUse	= nullif(@vLandUse,''),
Easements	= nullif(@vEasements,''),
OwnerType	= nullif(@vOwnerType,''),
OwnerName	= nullif(@vOwnerName,''),
LotArea	= nullif(@vLotArea,''),
BldgArea	= nullif(@vBldgArea,''),
ComArea	= nullif(@vComArea,''),
ResArea	= nullif(@vResArea,''),
OfficeArea	= nullif(@vOfficeArea,''),
RetailArea	= nullif(@vRetailArea,''),
GarageArea	= nullif(@vGarageArea,''),
StrgeArea	= nullif(@vStrgeArea,''),
FactryArea	= nullif(@vFactryArea,''),
OtherArea	= nullif(@vOtherArea,''),
AreaSource	= nullif(@vAreaSource,''),
NumBldgs	= nullif(@vNumBldgs,''),
NumFloors	= nullif(@vNumFloors,''),
UnitsRes	= nullif(@vUnitsRes,''),
UnitsTotal	= nullif(@vUnitsTotal,''),
LotFront	= nullif(@vLotFront,''),
LotDepth	= nullif(@vLotDepth,''),
BldgFront	= nullif(@vBldgFront,''),
BldgDepth	= nullif(@vBldgDepth,''),
Ext	= nullif(@vExt,''),
ProxCode	= nullif(@vProxCode,''),
IrrLotCode	= nullif(@vIrrLotCode,''),
LotType	= nullif(@vLotType,''),
BsmtCode	= nullif(@vBsmtCode,''),
AssessLand	= nullif(@vAssessLand,''),
AssessTot	= nullif(@vAssessTot,''),
ExemptLand	= nullif(@vExemptLand,''),
ExemptTot	= nullif(@vExemptTot,''),
YearBuilt	= nullif(@vYearBuilt,''),
YearAlter1	= nullif(@vYearAlter1,''),
YearAlter2	= nullif(@vYearAlter2,''),
HistDist	= nullif(@vHistDist,''),
Landmark	= nullif(@vLandmark,''),
BuiltFAR	= nullif(@vBuiltFAR,''),
ResidFAR	= nullif(@vResidFAR,''),
CommFAR	= nullif(@vCommFAR,''),
FacilFAR	= nullif(@vFacilFAR,''),
BoroCode	= nullif(@vBoroCode,''),
BBL	= nullif(@vBBL,''),
CondoNo	= nullif(@vCondoNo,''),
Tract2010	= nullif(@vTract2010,''),
XCoord	= nullif(@vXCoord,''),
YCoord	= nullif(@vYCoord,''),
ZoneMap	= nullif(@vZoneMap,''),
ZMCode	= nullif(@vZMCode,''),
Sanborn	= nullif(@vSanborn,''),
TaxMap	= nullif(@vTaxMap,''),
EDesigNum	= nullif(@vEDesigNum,''),
APPBBL	= nullif(@vAPPBBL,''),
APPDate	= STR_TO_DATE(nullif(@vAPPDate,''),'%m/%d/%Y'),
PLUTOMapID	= nullif(@vPLUTOMapID,''),
Version	= nullif(@vVersion,'');
